name: plotastrodata
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - astropy>=7.2
  - corner
  - dynesty
  - emcee>=3.1.5
  - matplotlib
  - numpy>=2.0
  - pillow
  - plotly
  - ptemcee
  - scikit-image
  - scipy
  - tqdm
